# Generated by Django 4.2.6 on 2023-10-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_apellido', models.CharField(max_length=150, verbose_name='Nombre y Apellido')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('problema', models.TextField(max_length=1000, verbose_name='Problema con el dispositivo')),
                ('estado', models.CharField(choices=[('En produccion', 'En produccion'), ('Listo para retirar', 'Listo para retirar'), ('Aceptado', 'Aceptado')], max_length=20, verbose_name='Estado en el que se encuentra el pedido')),
                ('codigo', models.CharField(default=1, max_length=50, verbose_name='Codigo de seguimiento')),
            ],
        ),
    ]
