# Generated by Django 4.2.6 on 2023-11-04 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo', models.CharField(default='uOVPnMd0lK', max_length=10, verbose_name='codigo de seguimiento')),
                ('fecha_deja_prod', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha entrada')),
                ('nombre_apellido', models.CharField(default='', max_length=126, verbose_name='Nombre y Apellido')),
                ('telefono_contacto', models.CharField(blank=True, default='+54', max_length=40, verbose_name='Telefono de contacto')),
                ('direccion', models.CharField(blank=True, default='', max_length=256, verbose_name='Direccion')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electronico')),
                ('equipo', models.CharField(blank=True, default='', max_length=126, verbose_name='Equipo')),
                ('marca_equipo', models.CharField(blank=True, default='', max_length=126, verbose_name='Marca del equipo')),
                ('modelo_equipo', models.CharField(blank=True, default='', max_length=126, verbose_name='Modelo del equipo')),
                ('numero_serie', models.CharField(blank=True, default='', max_length=126, verbose_name='Numero de serie del equipo')),
                ('imei', models.IntegerField(blank=True, default=0, verbose_name='Imei del equipo')),
                ('descripcion_problema', models.TextField(blank=True, default='', max_length=512, verbose_name='Breve descripcion del problema')),
                ('tipo_reparacion', models.CharField(choices=[('Reparacion por garantia', 'Reparacion por garantia'), ('reparacion por cuenta del cliente', 'reparacion por cuenta del cliente')], default='', max_length=200, verbose_name='tipo de reparacion')),
                ('fisuras', models.CharField(default='-----------', max_length=150, verbose_name='Fisuras/Quebraduras')),
                ('pintura', models.CharField(default='-----------', max_length=150, verbose_name='Pintura dañada')),
                ('marcas', models.CharField(default='-----------', max_length=150, verbose_name='Marcas/Rayones')),
                ('golpes_graves', models.CharField(default='-----------', max_length=150, verbose_name='Golpes Graves')),
                ('manchas', models.CharField(default='-----------', max_length=150, verbose_name='Manchas')),
                ('golpes_leves', models.CharField(default='-----------', max_length=150, verbose_name='Golpes leves')),
                ('componentes_faltantes', models.CharField(default='-----------', max_length=150, verbose_name='Componentes Faltantes')),
                ('otros', models.CharField(default='-----------', max_length=150, verbose_name='Otros')),
                ('observaciones', models.TextField(blank=True, default='', max_length=512, verbose_name='Otras Observaciones')),
                ('objectos', models.TextField(blank=True, default='', max_length=512, verbose_name='Objectos que dejo')),
                ('fecha_terminacion_prod', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha Salida')),
                ('monto_total', models.IntegerField(blank=True, default=0, verbose_name='Monto total (Aprox)')),
                ('tecnico', models.CharField(blank=True, default='', max_length=50, verbose_name='Tecnico encargado')),
                ('parte_pago', models.IntegerField(blank=True, default=0, verbose_name='Pago por adelantado')),
                ('estado', models.CharField(blank=True, choices=[('En produccion', 'En produccion'), ('Listo para retirar', 'Listo para retirar'), ('Aceptado', 'Aceptado')], max_length=20, verbose_name='Estado del pedido')),
            ],
        ),
    ]
