# Generated by Django 4.2.6 on 2023-11-04 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='RAXDj8c1I7', max_length=10, verbose_name='codigo de seguimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='componentes_faltantes',
            field=models.CharField(default='', max_length=150, verbose_name='Componentes Faltantes'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descripcion_problema',
            field=models.TextField(default='', max_length=512, verbose_name='Breve descripcion del problema'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=256, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='equipo',
            field=models.CharField(default='', max_length=126, verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('En produccion', 'En produccion'), ('Listo para retirar', 'Listo para retirar'), ('Aceptado', 'Aceptado')], max_length=20, verbose_name='Estado del pedido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_deja_prod',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha entrada'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_terminacion_prod',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Salida'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fisuras',
            field=models.CharField(default='', max_length=150, verbose_name='Fisuras/Quebraduras'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='golpes_graves',
            field=models.CharField(default='', max_length=150, verbose_name='Golpes Graves'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='golpes_leves',
            field=models.CharField(default='', max_length=150, verbose_name='Golpes leves'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imei',
            field=models.IntegerField(default=0, verbose_name='Imei del equipo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='manchas',
            field=models.CharField(default='', max_length=150, verbose_name='Manchas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='marca_equipo',
            field=models.CharField(default='', max_length=126, verbose_name='Marca del equipo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='marcas',
            field=models.CharField(default='', max_length=150, verbose_name='Marcas/Rayones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modelo_equipo',
            field=models.CharField(default='', max_length=126, verbose_name='Modelo del equipo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='monto_total',
            field=models.IntegerField(default=0, verbose_name='Monto total (Aprox)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_serie',
            field=models.CharField(default='', max_length=126, verbose_name='Numero de serie del equipo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='objectos',
            field=models.CharField(default='', max_length=512, verbose_name='Objectos que deja'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(default='', max_length=512, verbose_name='Otras Observaciones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='otros',
            field=models.CharField(default='', max_length=150, verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='parte_pago',
            field=models.IntegerField(default=0, verbose_name='Pago por adelantado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pintura',
            field=models.CharField(default='', max_length=150, verbose_name='Pintura dañada'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tecnico',
            field=models.CharField(default='', max_length=50, verbose_name='Tecnico encargado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_contacto',
            field=models.CharField(default='+54', max_length=40, verbose_name='Telefono de contacto'),
        ),
    ]
