# Generated by Django 4.2.6 on 2023-11-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_cliente_dibujo_patron_alter_cliente_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, default='ODuBFSItzC', max_length=10, null=True, verbose_name='codigo de seguimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dibujo_patron',
            field=models.IntegerField(default=0, verbose_name='Patron del usuario'),
        ),
    ]
