# Generated by Django 4.2.6 on 2023-11-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0010_alter_cliente_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='marca_equipo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero_serie',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, default='9pLZfQR8bg', max_length=10, null=True, verbose_name='codigo de seguimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_reparacion',
            field=models.CharField(blank=True, choices=[('Reparacion por garantia', 'Reparacion por garantia'), ('reparacion por cuenta del cliente', 'reparacion por cuenta del cliente')], default='reparacion por cuenta del cliente', max_length=200, null=True, verbose_name='tipo de reparacion'),
        ),
    ]
