# Generated by Django 4.2.6 on 2023-11-14 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0012_remove_cliente_componentes_faltantes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo', models.CharField(blank=True, default='100<django.db.models.fields.AutoField>', max_length=10, null=True, verbose_name='codigo de seguimiento')),
                ('fecha_deja_prod', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha entrada')),
                ('nombre_apellido', models.CharField(default='', max_length=126, null=True, verbose_name='Nombre y Apellido')),
                ('telefono_contacto', models.CharField(blank=True, default='+54', max_length=40, null=True, verbose_name='Telefono de contacto')),
                ('equipo', models.CharField(blank=True, default='', max_length=126, null=True, verbose_name='Equipo')),
                ('modelo_equipo', models.CharField(blank=True, default='', max_length=126, null=True, verbose_name='Modelo del equipo')),
                ('imei', models.IntegerField(blank=True, default=0, null=True, verbose_name='Imei del equipo')),
                ('descripcion_problema', models.TextField(blank=True, default='', max_length=512, null=True, verbose_name='Breve descripcion del problema')),
                ('tipo_reparacion', models.CharField(choices=[('Reparacion por garantia', 'Reparacion por garantia'), ('reparacion por cuenta del cliente', 'reparacion por cuenta del cliente')], default='reparacion por cuenta del cliente', max_length=200, verbose_name='tipo de reparacion')),
                ('fisuras', models.BooleanField(default=False, verbose_name='Fisuras/Quebraduras')),
                ('pintura', models.BooleanField(default=False, verbose_name='Pintura dañada')),
                ('marcas', models.BooleanField(default=False, verbose_name='Marcas/Rayones')),
                ('golpes_graves', models.BooleanField(default=False, verbose_name='Golpes Graves')),
                ('manchas', models.BooleanField(default=False, verbose_name='Manchas')),
                ('golpes_leves', models.BooleanField(default=False, verbose_name='Golpes leves')),
                ('otros', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Otros')),
                ('objectos', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Objectos que deja')),
                ('fecha_terminacion_prod', models.DateTimeField(verbose_name='Fecha Salida')),
                ('monto_total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Monto total (Aprox)')),
                ('tecnico', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Tecnico encargado')),
                ('parte_pago', models.IntegerField(blank=True, default=0, null=True, verbose_name='Pago por adelantado')),
                ('estado', models.CharField(blank=True, choices=[('En Arreglo', 'En Arreglo'), ('Listo para retirar', 'Listo para retirar'), ('Aceptado', 'Aceptado'), ('No se puede arreglar', 'No se puede arreglar')], max_length=20, null=True, verbose_name='Estado del pedido')),
                ('dibujo_patron', models.IntegerField(blank=True, default=0, verbose_name='Patron')),
                ('codigo_patron', models.CharField(blank=True, default='', max_length=100, verbose_name='Contrasena/Pin')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
