# Generated by Django 4.2.6 on 2023-11-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0013_servicio_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=500, verbose_name='Nombre del tecnico')),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(blank=True, choices=[('En Arreglo', 'En Arreglo'), ('Listo para retirar', 'Listo para retirar'), ('Aceptado', 'Aceptado'), ('No se puede arreglar', 'No se puede arreglar')], default='Aceptado', max_length=20, null=True, verbose_name='Estado del pedido'),
        ),
    ]
