# Generated by Django 4.2.6 on 2023-11-19 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0014_tecnico_alter_servicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cliente.tecnico'),
        ),
    ]
