# Generated by Django 4.2.6 on 2023-11-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0016_servicio_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='codigo de seguimiento'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='mensaje',
            field=models.TextField(max_length=500, null=True, verbose_name='Mensaje que se enviara'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='objectos',
            field=models.TextField(blank=True, default='', max_length=512, null=True, verbose_name='Objectos que deja'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='telefono_contacto',
            field=models.CharField(blank=True, default='+549', max_length=40, null=True, verbose_name='Telefono de contacto'),
        ),
    ]
