# Generated by Django 4.2.6 on 2024-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0017_alter_servicio_codigo_alter_servicio_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(blank=True, choices=[('En Arreglo', 'En Arreglo'), ('Listo para retirar', 'Listo para retirar'), ('Aceptado', 'Aceptado'), ('No se puede arreglar', 'No se puede arreglar'), ('ENTREGADO', 'ENTREGADO')], default='Aceptado', max_length=20, null=True, verbose_name='Estado del pedido'),
        ),
    ]
